services:
  - type: web
    name: hra-sms-app
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app --worker-class gevent -w 1 -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
