services:
  - type: web
    name: hra-sms-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class eventlet -w 1 -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
